### ISSUE TITLE
Unlock clearance request after leaving

### ISSUE THREAD

**Issue by erikquinn** [czqoocavatsim/nattrakv1#25]
- from the list of pending clearance requests, open one
- that clearance will appear as "locked" on the list while you are viewing it
- leave the page (by going back or by closing the tab)
- even after time passes, that clearance still shows as locked to other controllers

The resulting issue here is that if someone opens a clearance request by accident, or just to look, there doesn't seem to be any way for the controller who needs it to do anything with the request, due to it still being locked.

**Comment by liessdow** [comment]
#38 provides a fix, let me know if the default time (5 minutes to unlock) should be changed
